### ISSUE TITLE
Can I check total number of sessions/hours/minutes?

### ISSUE THREAD

**Issue by aamajzoub** [YetAnotherPomodoroApp/YAPA-2#57]
Hello there,
Is there a way to check the total number of sessions or time worked?
Thanks

**Comment by floatas** [comment]
Hi, currently there is no way to do that, but I think that it would be great addition.

**Comment by Digital-Coder** [comment]
I agree, I missed this feature too.

**Comment by floatas** [comment]
Since previous update we can select number of months in dashboard 
![image](https://user-images.githubusercontent.com/7883111/204083075-4ad42b0b-98fa-4ea8-b6e4-93c30470cacc.png)
You can select one year, two years or any other period. Adjusting period you can get all time worked.

Closing this ticket.
