### ISSUE TITLE
Daily sum hours shown in dashboard graph are incorrect

### ISSUE THREAD

**Issue by stanleyrhodes** [YetAnotherPomodoroApp/YAPA-2#59]
The dashboard line graph of hours is incorrect. For example, for 12 pomodoros at 25 minutes each, it shows 3.33 hours. Most of my daily totals have strange remainder values, like 2.92 or 4.17. Since in my case the complete pomo is always 25 minutes, I would expect the remainder ending digit to only be 5 or 0.

I do also have it often showing that pomos I did today happened tomorrow, which has already been reported as a time zone bug. Perhaps these are connected.

**Comment by DerTrolde** [comment]
Well, for me it works just fine. The only thing i'd like to mention about the situation is it only counts working hours. And the digit it shows is not 3(h).33 min. The float num it shows after the dot is the persentage of the next hour. This means if you use 20 min work\5 min relax pomo - only work interval counts, which is 20min = 0.33h. That's why if you want the digit to be not a float number use different work intervals like 15 min (0.25h) or 30 min (0.5h).

**Comment by floatas** [comment]
Thank you for reporting an issue, and thank you @DerTrolde  for investigating the issue. I'm not sure if pause should be included in total time 🤔 maybe in brackets. But I think time formatting should be fixed to show normal 3h 20min instead of 3.333

**Comment by DerTrolde** [comment]
@floatas Well, i didn't have any problems about how it works now, but probably normal time would be a nice update indeed. I agree that pause time should not be included in total time, since the most times i just skip pause myself. 😄

**Comment by floatas** [comment]
![image](https://user-images.githubusercontent.com/7883111/150647831-13545618-dc6e-47cc-99af-ae3182cc2b79.png)
 
Ready to release 🥳

**Comment by DerTrolde** [comment]
Awesome! Thanks so much for getting back to the app! 😊🙏
